"""Add dernier_releve to capteur

Revision ID: 6f4503a45a2f
Revises: cf7c73856195
Create Date: 2026-04-24 20:24:59.028410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4503a45a2f'
down_revision = 'cf7c73856195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actionneur', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='pompe_alimentation, pompe_evacuation, eclairage',
               existing_nullable=True)

    with op.batch_alter_table('alerte', schema=None) as batch_op:
        batch_op.alter_column('type_alerte',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='derive_ec, derive_temp, niveau_bas, panne...',
               existing_nullable=True)
        batch_op.alter_column('severite',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='info, warning, critique',
               existing_nullable=True,
               existing_server_default=sa.text("'info'::character varying"))
        batch_op.drop_index(batch_op.f('idx_alerte_cycle'))
        batch_op.drop_index(batch_op.f('idx_alerte_severite'))
        batch_op.drop_constraint(batch_op.f('alerte_id_utilisateur_ack_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('alerte_id_cycle_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('alerte_id_capteur_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cycle_culture', ['id_cycle'], ['id_cycle'])
        batch_op.create_foreign_key(None, 'utilisateur', ['id_utilisateur_ack'], ['id_utilisateur'])
        batch_op.create_foreign_key(None, 'capteur', ['id_capteur'], ['id_capteur'])

    with op.batch_alter_table('capteur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dernier_releve', sa.Numeric(), nullable=True))
        batch_op.alter_column('type_capteur',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='EC, temp_eau, temp_air, humidite, luminosite, niveau_eau',
               existing_nullable=True)

    with op.batch_alter_table('commande_actionneur', schema=None) as batch_op:
        batch_op.alter_column('etat',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='ON, OFF',
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=15),
               comment=None,
               existing_comment='automatique, manuel',
               existing_nullable=True,
               existing_server_default=sa.text("'automatique'::character varying"))
        batch_op.drop_index(batch_op.f('idx_commande_cycle'))
        batch_op.drop_constraint(batch_op.f('commande_actionneur_id_utilisateur_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('commande_actionneur_id_cycle_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('commande_actionneur_id_actionneur_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'utilisateur', ['id_utilisateur'], ['id_utilisateur'])
        batch_op.create_foreign_key(None, 'cycle_culture', ['id_cycle'], ['id_cycle'])
        batch_op.create_foreign_key(None, 'actionneur', ['id_actionneur'], ['id_actionneur'])

    with op.batch_alter_table('cycle_culture', schema=None) as batch_op:
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='en_cours, termine, abandonne',
               existing_nullable=True,
               existing_server_default=sa.text("'en_cours'::character varying"))
        batch_op.alter_column('date_recolte_predite',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Bonus: prédiction date de récolte',
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('cycle_culture_id_recette_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('cycle_culture_id_utilisateur_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('cycle_culture_id_variete_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recette_culture', ['id_recette'], ['id_recette'])
        batch_op.create_foreign_key(None, 'variete_plante', ['id_variete'], ['id_variete'])
        batch_op.create_foreign_key(None, 'utilisateur', ['id_utilisateur'], ['id_utilisateur'])

    with op.batch_alter_table('lecture_capteur', schema=None) as batch_op:
        batch_op.alter_column('qualite',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='ok, suspect, erreur',
               existing_nullable=True,
               existing_server_default=sa.text("'ok'::character varying"))
        batch_op.drop_index(batch_op.f('idx_lecture_capteur_capteur'))
        batch_op.drop_index(batch_op.f('idx_lecture_capteur_cycle'))
        batch_op.drop_index(batch_op.f('idx_lecture_capteur_horodatage'))
        batch_op.drop_constraint(batch_op.f('lecture_capteur_id_capteur_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('lecture_capteur_id_cycle_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'capteur', ['id_capteur'], ['id_capteur'])
        batch_op.create_foreign_key(None, 'cycle_culture', ['id_cycle'], ['id_cycle'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('canal',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='email, sms',
               existing_nullable=True)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=15),
               comment=None,
               existing_comment='en_attente, envoyee, echec',
               existing_nullable=True,
               existing_server_default=sa.text("'en_attente'::character varying"))
        batch_op.drop_index(batch_op.f('idx_notification_statut'))
        batch_op.drop_constraint(batch_op.f('notification_id_utilisateur_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('notification_id_alerte_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'alerte', ['id_alerte'], ['id_alerte'])
        batch_op.create_foreign_key(None, 'utilisateur', ['id_utilisateur'], ['id_utilisateur'])

    with op.batch_alter_table('rapport', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='rendement, croissance, resume_cycle',
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('rapport_id_utilisateur_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('rapport_id_cycle_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cycle_culture', ['id_cycle'], ['id_cycle'])
        batch_op.create_foreign_key(None, 'utilisateur', ['id_utilisateur'], ['id_utilisateur'])

    with op.batch_alter_table('recette_culture', schema=None) as batch_op:
        batch_op.alter_column('phase',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='germination, croissance, floraison, recolte',
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('recette_culture_id_variete_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'variete_plante', ['id_variete'], ['id_variete'])

    with op.batch_alter_table('suivi_croissance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('suivi_croissance_id_utilisateur_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('suivi_croissance_id_cycle_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'cycle_culture', ['id_cycle'], ['id_cycle'])
        batch_op.create_foreign_key(None, 'utilisateur', ['id_utilisateur'], ['id_utilisateur'])

    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='admin, operateur',
               existing_nullable=True,
               existing_server_default=sa.text("'operateur'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               comment='admin, operateur',
               existing_nullable=True,
               existing_server_default=sa.text("'operateur'::character varying"))

    with op.batch_alter_table('suivi_croissance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('suivi_croissance_id_cycle_fkey'), 'cycle_culture', ['id_cycle'], ['id_cycle'], deferrable=True)
        batch_op.create_foreign_key(batch_op.f('suivi_croissance_id_utilisateur_fkey'), 'utilisateur', ['id_utilisateur'], ['id_utilisateur'], deferrable=True)

    with op.batch_alter_table('recette_culture', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recette_culture_id_variete_fkey'), 'variete_plante', ['id_variete'], ['id_variete'], deferrable=True)
        batch_op.alter_column('phase',
               existing_type=sa.VARCHAR(length=20),
               comment='germination, croissance, floraison, recolte',
               existing_nullable=True)

    with op.batch_alter_table('rapport', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rapport_id_cycle_fkey'), 'cycle_culture', ['id_cycle'], ['id_cycle'], deferrable=True)
        batch_op.create_foreign_key(batch_op.f('rapport_id_utilisateur_fkey'), 'utilisateur', ['id_utilisateur'], ['id_utilisateur'], deferrable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               comment='rendement, croissance, resume_cycle',
               existing_nullable=True)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notification_id_alerte_fkey'), 'alerte', ['id_alerte'], ['id_alerte'], deferrable=True)
        batch_op.create_foreign_key(batch_op.f('notification_id_utilisateur_fkey'), 'utilisateur', ['id_utilisateur'], ['id_utilisateur'], deferrable=True)
        batch_op.create_index(batch_op.f('idx_notification_statut'), ['statut'], unique=False)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=15),
               comment='en_attente, envoyee, echec',
               existing_nullable=True,
               existing_server_default=sa.text("'en_attente'::character varying"))
        batch_op.alter_column('canal',
               existing_type=sa.VARCHAR(length=10),
               comment='email, sms',
               existing_nullable=True)

    with op.batch_alter_table('lecture_capteur', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lecture_capteur_id_cycle_fkey'), 'cycle_culture', ['id_cycle'], ['id_cycle'], deferrable=True)
        batch_op.create_foreign_key(batch_op.f('lecture_capteur_id_capteur_fkey'), 'capteur', ['id_capteur'], ['id_capteur'], deferrable=True)
        batch_op.create_index(batch_op.f('idx_lecture_capteur_horodatage'), [sa.literal_column('horodatage DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_lecture_capteur_cycle'), ['id_cycle'], unique=False)
        batch_op.create_index(batch_op.f('idx_lecture_capteur_capteur'), ['id_capteur'], unique=False)
        batch_op.alter_column('qualite',
               existing_type=sa.VARCHAR(length=10),
               comment='ok, suspect, erreur',
               existing_nullable=True,
               existing_server_default=sa.text("'ok'::character varying"))

    with op.batch_alter_table('cycle_culture', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cycle_culture_id_variete_fkey'), 'variete_plante', ['id_variete'], ['id_variete'], deferrable=True)
        batch_op.create_foreign_key(batch_op.f('cycle_culture_id_utilisateur_fkey'), 'utilisateur', ['id_utilisateur'], ['id_utilisateur'], deferrable=True)
        batch_op.create_foreign_key(batch_op.f('cycle_culture_id_recette_fkey'), 'recette_culture', ['id_recette'], ['id_recette'], deferrable=True)
        batch_op.alter_column('date_recolte_predite',
               existing_type=sa.DATE(),
               comment='Bonus: prédiction date de récolte',
               existing_nullable=True)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=20),
               comment='en_cours, termine, abandonne',
               existing_nullable=True,
               existing_server_default=sa.text("'en_cours'::character varying"))

    with op.batch_alter_table('commande_actionneur', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('commande_actionneur_id_actionneur_fkey'), 'actionneur', ['id_actionneur'], ['id_actionneur'], deferrable=True)
        batch_op.create_foreign_key(batch_op.f('commande_actionneur_id_cycle_fkey'), 'cycle_culture', ['id_cycle'], ['id_cycle'], deferrable=True)
        batch_op.create_foreign_key(batch_op.f('commande_actionneur_id_utilisateur_fkey'), 'utilisateur', ['id_utilisateur'], ['id_utilisateur'], deferrable=True)
        batch_op.create_index(batch_op.f('idx_commande_cycle'), ['id_cycle'], unique=False)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=15),
               comment='automatique, manuel',
               existing_nullable=True,
               existing_server_default=sa.text("'automatique'::character varying"))
        batch_op.alter_column('etat',
               existing_type=sa.VARCHAR(length=5),
               comment='ON, OFF',
               existing_nullable=True)

    with op.batch_alter_table('capteur', schema=None) as batch_op:
        batch_op.alter_column('type_capteur',
               existing_type=sa.VARCHAR(length=30),
               comment='EC, temp_eau, temp_air, humidite, luminosite, niveau_eau',
               existing_nullable=True)
        batch_op.drop_column('dernier_releve')

    with op.batch_alter_table('alerte', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('alerte_id_capteur_fkey'), 'capteur', ['id_capteur'], ['id_capteur'], deferrable=True)
        batch_op.create_foreign_key(batch_op.f('alerte_id_cycle_fkey'), 'cycle_culture', ['id_cycle'], ['id_cycle'], deferrable=True)
        batch_op.create_foreign_key(batch_op.f('alerte_id_utilisateur_ack_fkey'), 'utilisateur', ['id_utilisateur_ack'], ['id_utilisateur'], deferrable=True)
        batch_op.create_index(batch_op.f('idx_alerte_severite'), ['severite'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerte_cycle'), ['id_cycle'], unique=False)
        batch_op.alter_column('severite',
               existing_type=sa.VARCHAR(length=10),
               comment='info, warning, critique',
               existing_nullable=True,
               existing_server_default=sa.text("'info'::character varying"))
        batch_op.alter_column('type_alerte',
               existing_type=sa.VARCHAR(length=30),
               comment='derive_ec, derive_temp, niveau_bas, panne...',
               existing_nullable=True)

    with op.batch_alter_table('actionneur', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=30),
               comment='pompe_alimentation, pompe_evacuation, eclairage',
               existing_nullable=True)

    # ### end Alembic commands ###
