"""Add auto mode to actionneurs

Revision ID: 91df22b5b5fa
Revises: 6f4503a45a2f
Create Date: 2026-04-24 20:46:13.133980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91df22b5b5fa'
down_revision = '6f4503a45a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actionneur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode_automatique', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actionneur', schema=None) as batch_op:
        batch_op.drop_column('mode_automatique')

    # ### end Alembic commands ###
