"""Init

Revision ID: cf7c73856195
Revises: 
Create Date: 2026-04-24 11:26:14.600524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7c73856195'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actionneur',
    sa.Column('id_actionneur', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('port_serie', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_actionneur')
    )
    op.create_table('capteur',
    sa.Column('id_capteur', sa.Integer(), nullable=False),
    sa.Column('type_capteur', sa.String(length=30), nullable=True),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=False),
    sa.Column('valeur_min_possible', sa.Numeric(), nullable=True),
    sa.Column('valeur_max_possible', sa.Numeric(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('port_serie', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_capteur')
    )
    op.create_table('utilisateur',
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_utilisateur'),
    sa.UniqueConstraint('email')
    )
    op.create_table('variete_plante',
    sa.Column('id_variete', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duree_croissance_jours', sa.Integer(), nullable=False),
    sa.Column('conditions_ideales', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_variete')
    )
    op.create_table('recette_culture',
    sa.Column('id_recette', sa.Integer(), nullable=False),
    sa.Column('id_variete', sa.Integer(), nullable=True),
    sa.Column('nom_recette', sa.String(length=150), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=True),
    sa.Column('ec_min', sa.Numeric(), nullable=True),
    sa.Column('ec_max', sa.Numeric(), nullable=True),
    sa.Column('temp_eau_min', sa.Numeric(), nullable=True),
    sa.Column('temp_eau_max', sa.Numeric(), nullable=True),
    sa.Column('temp_air_min', sa.Numeric(), nullable=True),
    sa.Column('temp_air_max', sa.Numeric(), nullable=True),
    sa.Column('humidite_min', sa.Numeric(), nullable=True),
    sa.Column('humidite_max', sa.Numeric(), nullable=True),
    sa.Column('luminosite_min', sa.Numeric(), nullable=True),
    sa.Column('luminosite_max', sa.Numeric(), nullable=True),
    sa.Column('luminosite_heures_jour', sa.Integer(), nullable=True),
    sa.Column('niveau_eau_min', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['id_variete'], ['variete_plante.id_variete'], ),
    sa.PrimaryKeyConstraint('id_recette')
    )
    op.create_table('cycle_culture',
    sa.Column('id_cycle', sa.Integer(), nullable=False),
    sa.Column('id_variete', sa.Integer(), nullable=True),
    sa.Column('id_recette', sa.Integer(), nullable=True),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin_prevue', sa.Date(), nullable=True),
    sa.Column('date_fin_reelle', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_recolte_predite', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_recette'], ['recette_culture.id_recette'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.ForeignKeyConstraint(['id_variete'], ['variete_plante.id_variete'], ),
    sa.PrimaryKeyConstraint('id_cycle')
    )
    op.create_table('alerte',
    sa.Column('id_alerte', sa.BigInteger(), nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_capteur', sa.Integer(), nullable=True),
    sa.Column('type_alerte', sa.String(length=30), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('valeur_mesuree', sa.Numeric(), nullable=True),
    sa.Column('valeur_seuil', sa.Numeric(), nullable=True),
    sa.Column('severite', sa.String(length=10), nullable=True),
    sa.Column('horodatage', sa.DateTime(), nullable=True),
    sa.Column('acquittee', sa.Boolean(), nullable=True),
    sa.Column('horodatage_acquittement', sa.DateTime(), nullable=True),
    sa.Column('id_utilisateur_ack', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_capteur'], ['capteur.id_capteur'], ),
    sa.ForeignKeyConstraint(['id_cycle'], ['cycle_culture.id_cycle'], ),
    sa.ForeignKeyConstraint(['id_utilisateur_ack'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_alerte')
    )
    op.create_table('commande_actionneur',
    sa.Column('id_commande', sa.BigInteger(), nullable=False),
    sa.Column('id_actionneur', sa.Integer(), nullable=True),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('etat', sa.String(length=5), nullable=True),
    sa.Column('duree_secondes', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=15), nullable=True),
    sa.Column('horodatage', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_actionneur'], ['actionneur.id_actionneur'], ),
    sa.ForeignKeyConstraint(['id_cycle'], ['cycle_culture.id_cycle'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_commande')
    )
    op.create_table('lecture_capteur',
    sa.Column('id_lecture', sa.BigInteger(), nullable=False),
    sa.Column('id_capteur', sa.Integer(), nullable=True),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('valeur', sa.Numeric(), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=True),
    sa.Column('qualite', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id_capteur'], ['capteur.id_capteur'], ),
    sa.ForeignKeyConstraint(['id_cycle'], ['cycle_culture.id_cycle'], ),
    sa.PrimaryKeyConstraint('id_lecture')
    )
    op.create_table('rapport',
    sa.Column('id_rapport', sa.Integer(), nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('date_generation', sa.DateTime(), nullable=True),
    sa.Column('chemin_pdf', sa.String(length=500), nullable=True),
    sa.Column('rendement_g', sa.Numeric(), nullable=True),
    sa.Column('consommation_eau_l', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['cycle_culture.id_cycle'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_rapport')
    )
    op.create_table('suivi_croissance',
    sa.Column('id_suivi', sa.Integer(), nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('date_mesure', sa.Date(), nullable=False),
    sa.Column('hauteur_cm', sa.Numeric(), nullable=True),
    sa.Column('poids_g', sa.Numeric(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['cycle_culture.id_cycle'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_suivi')
    )
    op.create_table('notification',
    sa.Column('id_notification', sa.BigInteger(), nullable=False),
    sa.Column('id_alerte', sa.BigInteger(), nullable=True),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('canal', sa.String(length=10), nullable=True),
    sa.Column('statut', sa.String(length=15), nullable=True),
    sa.Column('horodatage', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_alerte'], ['alerte.id_alerte'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateur.id_utilisateur'], ),
    sa.PrimaryKeyConstraint('id_notification')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('suivi_croissance')
    op.drop_table('rapport')
    op.drop_table('lecture_capteur')
    op.drop_table('commande_actionneur')
    op.drop_table('alerte')
    op.drop_table('cycle_culture')
    op.drop_table('recette_culture')
    op.drop_table('variete_plante')
    op.drop_table('utilisateur')
    op.drop_table('capteur')
    op.drop_table('actionneur')
    # ### end Alembic commands ###
